// <auto-generated />
namespace FSDTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initialr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialr));
        
        string IMigrationMetadata.Id
        {
            get { return "201411280652397_initialr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
